### ISSUE TITLE
Animation of switching views

### ISSUE THREAD

**Issue by Asthestarsfalll** [r0-zero/picom#11]
Hi, thank you so much for this wonderful picom fork!
I am wondering that if the picom can set animation of switching views to 'from top to down' like this:
https://github.com/FT-Labs/phyOS-dwm/blob/screenshots/screenshots/g2.gif
![image](https://github.com/FT-Labs/phyOS-dwm/blob/screenshots/screenshots/g2.gif)
Now it's from left to right

**Comment by r0-zero** [comment]
Thanks! Check the picom.sample.conf, or download https://github.com/FT-Labs/physettings, a tui app that you can choose any animation you want from it then save the settings
