### ISSUE TITLE
Animations for specific window types

### ISSUE THREAD

**Issue by ModestTom** [r0-zero/picom#12]
### Platform

Arch Linux

### Environment

bspwm
### picom version

vgit-c8665

### Other details

I just want to say I love this fork. It's the most feature heavy with the least amount of bugs. In regards to the animations, I was wondering if there was a way to assign specific animations to specific window types? Thank you and keep up the good work!

**Comment by r0-zero** [comment]
Hello,

Thanks for your review! You can add animation for specific window types, but it is only for open window currently. 
You can add animation = your_open_win_anim_preference; in the usual window types section. Maybe I will add other ones later as a patch, but currently I'm so busy with releasing debian and arch isos, it will wait for some time.

**Comment by ikz87** [comment]
Hi, I'm not sure if the example you gave is correctly implemented yet. 
<video src="https://user-images.githubusercontent.com/98569017/213522882-18ff2c51-1698-4a45-8f67-67167c13fd8c.mp4"></video>
It seems to work to deactivate the animation, but when I try to overwrite the animation it just uses the one set at `animation-for-open-window`

**Comment by r0-zero** [comment]
Fixed! You can now use any animation you want. I will implement per class base animation soon I hope.

**Comment by ikz87** [comment]
Thank you! I do think per class animation settings would be such a nice addition, take your time! :)
