### ISSUE TITLE
Animation sometimes not triggered when opening winows

### ISSUE THREAD

**Issue by musjj** [r0-zero/picom#26]
### Platform
NixOS 23.11

### GPU, drivers, and screen setup

NVIDIA GeForce GT 635, nvidia 470.199.02
<details>
<summary><code>glxinfo -B</code></summary>

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 2048 MB
    Total available memory: 2048 MB
    Currently available dedicated video memory: 1738 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GT 635/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 470.199.02
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 470.199.02
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 470.199.02
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```
</details>

### Environment
AwesomeWM

### picom version
v10
<details>
<summary>Diagnostics</summary>

**Version:** v10

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: $HOME/.config/picom/picom.conf

### Drivers (inaccurate):

NVIDIA

### Backend: glx

* Driver vendors:
 * GLX: NVIDIA Corporation
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GT 635/PCIe/SSE2

### Backend: egl

* Driver vendors:
 * EGL: NVIDIA
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GT 635/PCIe/SSE2
</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
active-opacity = 1.000000;
animation-for-next-tag = "slide-in-center";
animation-for-open-window = "zoom";
animation-for-prev-tag = "minimize";
animation-for-transient-window = "slide-up";
animation-for-unmap-window = "squeeze";
animation-stiffness-tag-change = 90.000000;
animations = true;
backend = "glx";
corner-radius = 8;
detect-client-opacity = true;
detect-rounded-corners = true;
enable-fading-next-tag = true;
enable-fading-prev-tag = true;
fade-delta = 10;
fade-exclude = [  ];
fade-in-step = 0.080000;
fade-out-step = 0.080000;
fading = true;
glx-no-rebind-pixmap = true;
glx-no-stencil = true;
inactive-opacity = 1.000000;
log-level = "warn";
no-use-damage = true;
opacity-rule = [  ];
rounded-corners-exclude = [ "window_type = 'desktop'" , "window_type = 'menu'" , "class_i = 'dunst'" ];
shadow = false;
shadow-exclude = [  ];
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-opacity = 0.750000;
unredir-if-possible = false;
vsync = true;
wintypes: { dropdown_menu = { opacity = 1.000000; }; popup_menu = { opacity = 1.000000; }; };
xrender-sync-fence = true;
```
</details>

### Steps of reproduction

1. Switch to `tile` layout
2. Open a new window several times

### Expected behavior

Animation always plays.

### Current Behavior

Sometimes the animation is triggered, but most often it is not.

### Other details

I found these in the logs:

```
Sep 01 13:59:43 $HOST picom[180087]: Xlib: ignoring invalid extension event 161
Sep 01 13:59:43 $HOST picom[180087]: Xlib: ignoring invalid extension event 161
Sep 01 13:59:43 $HOST picom[180087]: Xlib: ignoring invalid extension event 161
Sep 01 13:59:43 $HOST picom[180087]: Xlib: ignoring invalid extension event 161
Sep 01 13:59:43 $HOST picom[180087]: [ 09/01/2023 13:59:43.927 x_log_error WARN ] X error 3 WINDOW request 2 minor 0 serial 964500
```
In particular, the `ignoring invalid extension event *` message is repeated *a lot*.

**Comment by r0-zero** [comment]
Okay the  most broken WM is awesomewm right now, and I actually don't know why. 

Do you have any idea if it reparents the windows or not? Just a guess, but the error felt to me like it is spawning child windows that is connected to another window not new Xwindows.

**Comment by musjj** [comment]
Personally, this issue has been following me from bspwm, AwesomeWM and now Qtile. So I'm not sure how WM-specific the issue is. Can you tell me how to check if it's reparenting windows?

Another interesting point: animations for floating windows always work.

**Comment by r0-zero** [comment]
You could try to check output of this:

xwininfo -root -children

**Comment by musjj** [comment]
This is the output:

```
xwininfo: Window id: 0x28d (the root window) (has no name)

  Root window id: 0x28d (the root window) (has no name)
  Parent window id: 0x0 (none)
     24 children:
     0x160006d "Firefox": ("Firefox" "firefox")  383x620+930+128  +930+128
     0x1600071 "Firefox": ("firefox" "firefox")  200x200+0+0  +0+0
     ...
```

It does look like there's a parent window. Is this what you were talking about?

**Comment by r0-zero** [comment]
Yes, but that looks okay.

Could you try the next branch again? I have updated and fixed some minor issues in it.

**Comment by musjj** [comment]
It still has the same problem, unfortunately.

**Comment by r0-zero** [comment]
Can you try the latest commit? I think this resolves the issue, I have tried on awesome as well with the default config

**Comment by musjj** [comment]
The issue is still occurring for me in QTile. Can you try to reproduce the issue:
1. Open a new empty workspace
2. Open a new Kitty window

**Comment by r0-zero** [comment]
@musjj could you try again with latest one?
