### ISSUE TITLE
Windows only animating when initially opened

### ISSUE THREAD

**Issue by willothy** [r0-zero/picom#30]
### Platform
Arch 6.6.2, x86_64

### GPU, drivers, and screen setup
GTX 1080, nvidia 545.29.06, two monitors side by side (2560x1080, 1920x1080)

<details>
<summary>glxinfo</summary>
name of display: :1
display: :1  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 8192 MB
    Currently available dedicated video memory: 6335 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1080/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 545.29.06
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 545.29.06
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 545.29.06
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
</details>

### Environment

AwesomeWM

### picom version

vgit-c0ed4

<details>
<summary>Diagnostics</summary>

**Version:** vgit-c0ed4

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/willothy/.config/picom/picom.conf

### Drivers (inaccurate):

NVIDIA, modesetting

### Backend: glx

* Driver vendors:
 * GLX: NVIDIA Corporation
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2

### Backend: egl

* Driver vendors:
 * EGL: NVIDIA
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2
</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
**Version:** vgit-c0ed4

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/willothy/.config/picom/picom.conf

### Drivers (inaccurate):

NVIDIA, modesetting

### Backend: glx

* Driver vendors:
 * GLX: NVIDIA Corporation
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2

### Backend: egl

* Driver vendors:
 * EGL: NVIDIA
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2
```
</details>

### Steps of reproduction

1. Open a window
2. Minimize it
3. Reopen it, and it will appear but not animate

### Expected behavior

Windows should animate when being reopened.

### Current Behavior

Windows only animate when opened the first time, but when reopened they just fade in / appear in place. Movement / swap animations still work, but switching workspaces also only animates the first time a workspace is entered.

I'm not sure if this is intentional, but if it is then maybe this should be optional?

**Comment by willothy** [comment]
Maybe a duplicate of #26?

**Comment by r0-zero** [comment]
Hello,

Window animation only happens when a window is mapped or destroyed. This is the default behavior, minimizing will not trigger the open animation. It only applies for new windows and windows that are being closed.
