### ISSUE TITLE
Configuring dmenu animations

### ISSUE THREAD

**Issue by hsover** [r0-zero/picom#35]
I'm trying to configure the animations of dmenu but it isn't working. I've tried all the wintypes and only "normal" works but it affects all of the windows. How can I set a specific animation just for dmenu? And also what about browser GUIs like right click?

**Comment by r0-zero** [comment]
This is not implemented fully yet, will let you know when it is done

**Comment by BetaLost** [comment]
Switched to Hyprland so...
