### ISSUE TITLE
My PC makes a sound every time I move or open a window

### ISSUE THREAD

**Issue by iiKovu** [r0-zero/picom#38]
### Platform
Arch Linux 6.8.8-arch1-1

### GPU, drivers, and screen setup

**Version:** vgit-df4c6

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/kovu/.config/picom/picom.conf

### Drivers (inaccurate):

AMDGPU, Radeon

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: AMD
* GL renderer: AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 17.0.6, DRM 3.57, 6.8.8-arch1-1)
* Accelerated: 1

### Backend: egl

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: radeonsi
 * GL: AMD
* GL renderer: AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 17.0.6, DRM 3.57, 6.8.8-arch1-1)

### Configuration:
Basic config, almost default

</details>

### Steps of reproduction

    Enable animations, and when moving or opening a window, PC makes a sound. If I increase the "animation-stiffness-in-tag" value, sound when moving floating windows will be more silent with each increase.

### Expected behavior
   For it to not make a sound.

**Comment by iiKovu** [comment]
After doing some research, I think the sound is known as "coil whine". It happens only when doing stuff with the picom animations on.

**Comment by mentalhub** [comment]
> After doing some research, I think the sound is known as "coil whine". It happens only when doing stuff with the picom animations on.

Do you have sound system installed? if so, you can check what sound "coil whine" signalling for in your settings. It potentially can make an error sound on some DE.

**Comment by iiKovu** [comment]
> > After doing some research, I think the sound is known as "coil whine". It happens only when doing stuff with the picom animations on.
> 
> Do you have sound system installed? if so, you can check what sound "coil whine" signalling for in your settings. It potentially can make an error sound on some DE.

The sound is coming from my PC, hardware I mean. I don't have any sound system nor a DE installed, just Xorg and bspwm.

**Comment by mentalhub** [comment]
Oh, i get it. So its sound of your video card under load and its not Picom related.

**Comment by iiKovu** [comment]
> Oh, i get it. So its sound of your video card under load and its not Picom related.

I think it can be related. See, it happens just when I resize or move windows and the picom animations are enabled. My video card won't overload because of picom.

**Comment by Ari-43** [comment]
> > Oh, i get it. So its sound of your video card under load and its not Picom related.
> 
> I think it can be related. See, it happens just when I resize or move windows and the picom animations are enabled. My video card won't overload because of picom.

I've had situations where when my GPU, a 2080 Super with a slight factory overclock, will have coil whine under slight load (but it's either not there or downed out by fan noise under heavier loads). This isn't a picom issue, it's just how your GPU is.
