### ISSUE TITLE
Buggy shadows

### ISSUE THREAD

**Issue by PoSayDone** [r0-zero/picom#4]
### GPU, drivers, and screen setup
Gpu: Nvidia rtx 2060m
Driver: nvidia-dkms-520.56.06-2

### Environment
Bspwm/dwm/aweseom

### picom version
Cloned from repo
</details>

### Configuration:
Default phyos picom config with enabled shadows
</details>

### Steps of reproduction

1. Install picom
2. Enable shadows

### Expected behavior
![image](https://user-images.githubusercontent.com/29358657/197237507-efb8891a-484b-4e7f-96c5-cb62dd4cf0e0.png)

### Current Behavior
![image](https://user-images.githubusercontent.com/29358657/197237105-b296287a-4e4d-4bdf-bb7f-703b134b030b.png)
![image](https://user-images.githubusercontent.com/29358657/197237209-5941b963-9c02-4c75-83fd-34ff34622291.png)
![image](https://user-images.githubusercontent.com/29358657/197239524-1a2af048-e9ea-4c74-b904-545886da958b.png)

**Comment by r0-zero** [comment]
Yes, I can confirm this issue happens on my side too, with some animation glitches extra. I will take a look at it, but probably yshui/picom will handle it before than I do. I will merge it when it is handled.

**Comment by PoSayDone** [comment]
> Yes, I can confirm this issue happens on my side too, with some animation glitches extra. I will take a look at it, but probably yshui/picom will handle it before than I do. I will merge it when it is handled.

Okie, would close issue when it would be fixed

**Comment by r0-zero** [comment]
Animation glitches and performance issue have been fixed. Waiting for yshui to handle glx stuff.

**Comment by r0-zero** [comment]
Fixed with latest commit!

**Comment by ikz87** [comment]
The final feature I was waiting for, this is literally the perfect fork now lol ty :)
