### ISSUE TITLE
animation-for-open-window = "none" hide all windows

### ISSUE THREAD

**Issue by sunyuechi** [r0-zero/picom#6]
In new commit, 

```
animations = true;
animation-for-open-window = "none";
```

will hide all windows without restoring windows

use fly-in,zoom.... work ok, hope still support none

```
animations = true;
animation-for-open-window = "zoom";
```

### GPU, drivers, and screen setup
GPU: NVIDIA GeForce RTX 3060 

### Environment
awesomewm

### picom version

`vgit-260ad` + `animation-for-open-window = "none";` will hide the window without restoring windows (https://github.com/FT-Labs/picom/commit/260adcdc1578089811b75526459893b722b94b61)

`vgit-6fbc1` + `animation-for-open-window = "none";`  work ok  (https://github.com/FT-Labs/picom/commit/5a8da46952537d6077d2e864efc1fc367aaf6d40)

**Comment by r0-zero** [comment]
All right I will check this

**Comment by sunyuechi** [comment]
@FT-Labs Is there any progress on this issue?

**Comment by r0-zero** [comment]
Hello, could you try it again? I don't seem to have any issues while using "none"; now.

**Comment by sunyuechi** [comment]
@FT-Labs  thanks, no problem in new commit
